* Spacemacs Rocks Season 2 (Day 7)
** Tweak C-w to delete backward
C-w 向回删除一个字
(global-set-key (kbd "C-w") 'backward-kill-word)

init-packages:
(evil-mode 1)
(setcdr evil-insert-state-map nil)
(define-key evil-insert-state-map [escape] 'evil-normal-state)

** Evil (It's not Baidu!)   Turn Emacs into Vim in one second
1. install Evil plugin
evil-surround
(require 'evil-surround)
(global-evil-surround-mode 1)
v,i,w 选中一个单词，S '加两边引号; cs <old> <new> 改变原来surround.
注：(默认加空格，）是不加空格。


evil-nerd-commenter
(define-key evil-normal-state-map (kbd ",/") 'evilnc-comment-or-uncomment-lines)
(evilnc-default-hotkeys)
,/ 加注释或去注释标记

2. tell the different between Evil and Vim
   Universal args //C-u 原来的设置; M-x customize-group -evil -search:scroll C-u set 'on'

3. Evil state = Vim mode
evil normal state
evil insert state
evil visual state
evil motion state
evil emacs state
evil operator state (diw)
C-z 会转换模式

4. configure Evil leader key
(evil-leader/set-leader "<SPC>")

5. press `C-z` to toggle between Normal and Emacs state ??

6. Made some modes to use emacs-state
#+BEGIN_SRC emacs-lisp
 (dolist (mode '(ag-mode
                  flycheck-error-list-mode
                  git-rebase-mode))
    (add-to-list 'evil-emacs-state-modes mode))
#+END_SRC

6. binding h/j/k/l key
C-s C-j 进入目录 这时可以使用hjkl
M-s o 进入occur时，默认是normal state,如果希望是emacs state （即可使用hjkl) 则需以下配置。
#+BEGIN_SRC emacs-lisp
  (add-hook 'occur-mode-hook
            (lambda ()
              (evil-add-hjkl-bindings occur-mode-map 'emacs
                (kbd "/")       'evil-search-forward
                (kbd "n")       'evil-search-next
                (kbd "N")       'evil-search-previous
                (kbd "C-d")     'evil-scroll-down
                (kbd "C-u")     'evil-scroll-up
                ))
#+END_SRC
Add this to Dired mode, ibuffer mode?

** Which key
注：package-install找不到包时需要用package-refresh-contents来刷新。
(which-key-mode)后，当按空格键后，下面会提示出所有空格开头键组合。
** Design your own key bindings
1. Use SPC as the leader key
2. Use comma as the major mode leader key
3. Use SPC : to list all available commands
4. Use which key to group key bindings
5. Yeah! You got a minimal Spacemacs!

** Bonus Time:  Search  Org notes

** References

- https://www.emacswiki.org/emacs/Evil

- http://juanjoalvarez.net/es/detail/2014/sep/19/vim-emacsevil-chaotic-migration-guide/

- http://nathantypanski.com/blog/2014-08-03-a-vim-like-emacs-config.html

- http://blog.aaronbieber.com/2015/05/24/from-vim-to-emacs-in-fourteen-days.html

- http://blog.jakubarnold.cz/2014/06/23/evil-mode-how-to-switch-from-vim-to-emacs.html


** Exercises
- Install hydra and begin to add your own hydras!
