* Spacemacs Rocks Season 2 (Day 6)
** Bonus Time: Org-mdoe
Use org-capture to take notes
记笔记工具
#+BEGIN_SRC emacs-lisp

  (setq org-capture-templates
        '(("t" "Todo" entry (file+headline "~/.emacs.d/gtd.org" "工作安排")
           "* TODO [#B] %?\n  %i\n"
           :empty-lines 1)))
#+END_SRC
M-x org-capture
(global-set-key (kbd "C-c r") 'org-capture)
(setq org-agenda-files '("~/.emacs.d/"))
C-c a a ;;现在还没有列表（因为没定时间）
gtd.org里某一项：C-c C-s 定时间

安装org-pomodoro: packages; (require 'org-pomodoro)
M-x cust group /org-pomodoro
  long break length: 20 -> 40 ->save future

C-c a a 到某一项上 M-x org-pomodoro[return] 状态栏会显示任务信息。

注：C-x RET f utf-8 RET 存成utf-8
全局设置：(set-language-environment "UTF-8") 
Further reading:
http://orgmode.org/manual/Capture.html
*** Install Org pomodoro to track my time

** clean up configs
1. move keybindings into one place (init.el最后一行，其它el文件中的键绑定均集中在init-keybindings)
2. make c-n and c-p to select company condicate
search: emacs company c-n keybindings ;;将补全下拉列表时M-p/M-n改为C-p/C-n使统一风格
(with-eval-after-load 'company
  (define-key company-active-map (kbd "M-n") nil)
  (define-key company-active-map (kbd "M-p") nil)
  (define-key company-active-map (kbd "C-n") #'company-select-next)
  (define-key company-active-map (kbd "C-p") #'company-select-previous))
** Batch rename files
1. press `C-x C-q` in dired mode
C-x C-j 进入目录buffer. shift+6 进入上级目录。
+ 新建.emacs.d/test-dir
C-x C-f 创建文件hello.txt 输入hello. C 拷贝2个文件hello2.txt hello3.txt1. 
C-x C-q进入编辑模式，C=选中 C-c s e全部匹配，然后修改。C-c C-c 存盘。
M-x reveal-in-osx-finder 查看文件名是否已经修改成功（成功）

** search and replace
安装helm-ag
# Mac OS X 通过 Homebrew 安装
brew install the_silver_searcher

# Ubuntu 下安装
apt-get install silversearcher-ag

# Windows 下通过 msys2 安装（确保在 path 中）
pacman -S mingw-w64-i686-ag # 32 位电脑
pacman -S mingw-w64-x86_64-ag # 64 位电脑

C-c p s 进入查找模式
例：init org 找到3个结果
C-c C-e 进入结果可编辑模式，可类似batch rename files的操作。
** show js err with flycheck
flycheck-checkers
1.安装node.js
2.eslint
$ npm install -g eslint
$ eslint --init
3.激活flycheck
(global-flycheck-mode t);; 这时，连.el都有语法提示，我们是不希望这样的。所以：
  (add-hook 'js2-mode-hook 'flycheck-mode)
4.M-x flycheck-list-errors 列出所有错误
      flycheck-verify-setup 选择语法检查器
5. .eslintrc
** Snippets and auto snippet
yasnippet 是一个代码块补全的插件（GitHub 地址）。使用下面的配置文件将其在所有 的编程语言的模式中激活。
(yas-reload-all)
(add-hook 'prog-mode-hook #'yas-minor-mode)

菜单栏有YASnippet, 执行load everthing
这时，在test.js里敲for + <tab> 会补全出一个模板代码块. 还有log也可以。

auto-yasnippet:
1.加入init-packages
2.init-packages中加
  (smartparens-global-mode t)后加
  ;;(sp-local-pair 'emacs-lisp-mode "'" nil :actions nil)
  (sp-local-pair '(emacs-lisp-mode lisp-interaction-mode) "'" nil :actions nil)

3.加绑定
(global-set-key (kbd "H-w") #'aya-create)
(global-set-key (kbd "H-y") #'aya-expand)

4.测试：
  1.*scrach* buffer中写下面一行
  2.(add-to-listAA 'pathAA 'xxxAA)
  3.将AA前加～。即成下面一行
  4.(add-to-list~AA 'path~AA 'xxx~AA)
  5.M-x aya-create 建立模板
  6.buffer 空白处 M-x aya-expand 这时会出现与2.类似的行
  7.将AA 改为其它字，如BB。变为下列行
    (add-to-listAA 'pathAA 'xxxAA)
    (add-to-listBB 'pathBB 'xxxBB)
** exercises
1. give `helm-swoop` package a try: https://github.com/ShingoFukuyama/helm-swoop
2. Give `org-mac-link` package a try: http://melpa.org/#/org-mac-link
