* Spacemacs Rocks Season 2 (Day 4)                                      :TOC:
   - [[#split-your-configs-into-multiple-files][Split your configs into multiple files]]
   - [[#major-mode-and-minor-mode-in-details][Major mode and minor mode in details]]
   - [[#better-defaults][Better Defaults]]
   - [[#exercise][Exercise]]

** Split your configs into multiple files
1. use Git to management your init file
cd C:\Users\alan\AppData\Roaming\.emacs.d  -file/git bash here
$ git init
$ git add .
$ git commit -m "first commit"
//未提交前恢复
$ git checkout init.el
  (init.el 中需设置(global-auto-revert-mode t) 即当外部文件修改时不用重新打开此文件)
//auto-save-list 不参加备份
$ vim .gitignore +auto-save-list
$ git add .gitignore
$ git commit -m "add .gitignore"
注：(setq auto-save-default nil)貌似不起作用！

2. help window is anoyying.. 
解决帮助窗口打开后，光标没有定位到此窗口，导致需进入此窗口后再按Q。
#+BEGIN_SRC emacs-lisp
;; add popwin mode
;; why this line is needed
(require 'popwin) (require 'init-packages)
   ;;when require, wh(setq company-minimum-prefix-length 1)en not require
(popwin-mode t)
#+END_SRC

3. load-file, load-path and load
4. features, provide and require, autoload
5. naming conventions
zilongshanren/xxxx //变量名或函数名
minor mode or major mode. //命名mode最好带自己的前缀
niubi-mode
niubi-xxx 

   all of the names should have a prefix, such that the naming conflicts could be minimal.  
6. define your abbrevs
因为系统补全，如zilongshanren/packages，会补全很长的名字。为解决这种情况，就定义自己的缩写。
例：输入8ms加空格或其它非字母则会补全为: Mircsoft .
#+BEGIN_SRC emacs-lisp
  (setq-default abbrev-mode t)

  (define-abbrev-table 'global-abbrev-table '(
                                              ;; signature
                                              ("8zl" "zilongshanren")
                                              ;; emacs regex
                                              
                                              ))
#+END_SRC
7. how to organize your configs
- init-packages.el //包相关
- init-ui.el  //显示相关
- init-better-defaults.el  //默认值
- init-keybindings.el  //快捷键
- custom.el  //存放自动生成配置。如init.el最后
#+BEGIN_SRC emacs-lisp
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
#+END_SRC

8. use `counsel-git` to find file in git managed project.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c p f") 'counsel-git)
#+END_SRC


** Major mode and minor mode in details
1. conventions
text-mode/special-mode/prog-mode
naming:  xxx-mode,  xxx-mode-key-map  xxx-mode-hook

2. mode key map and mode hook

3. let's take a look at a pacakge in elpa (company)
   
** Better Defaults
1. disable audio bell
#+BEGIN_SRC emacs-lisp
  (setq ring-bell-function 'ignore)
#+END_SRC

2. auto revert file when they are changed outside the editor
#+BEGIN_SRC emacs-lisp
(global-auto-revert-mode t)
#+END_SRC

** Exercise
1. Only turn on Linum-mode when doing programming (tips: use prog-mode-hook)
